#!/bin/sh

openscad -o chamber.stl -D PARTNO=1 custom-ecr3.scad
openscad -o sheath.stl -D PARTNO=2 custom-ecr3.scad
openscad -o injection_surface.stl -D PARTNO=3 custom-ecr3.scad
openscad -o extraction_surface.stl -D PARTNO=4 custom-ecr3.scad
