#!/bin/sh

exec cmake . -DCGAL_DIR='../../../cgal-releases-CGAL-4.9-branch/build' \
    -DCMAKE_CXX_FLAGS='-std=c++14 -Wall -frounding-math' \
    -DCMAKE_BUILD_TYPE=Release -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=TRUE

